image: php:7.4

pipelines:
  default:
    - step:
        name: Deploy to Test
        deployment: test
        caches:
          - rsync-cache
        script:
          - apt-get update && apt-get install -y rsync  # Install rsync
          - rsync -avz --delete --checksum ./public_html/ $FTP_USERNAME@$FTP_SERVER:/ruta/remota/

definitions:
  caches:
    rsync-cache: /var/cache/apt/archives