image: php:7.4

pipelines:
  default:
    - step:
        name: Deploy to Test
        deployment: test
        caches:
          - rsync-cache # Nombre válido del caché
        script:
          # Instalación de curlftpfs y rsync solo si no están en caché
          - apt-get update && apt-get install -y curlftpfs rsync # Instala curlftpfs y rsync
          - mkdir -p /mnt/ftp
          - curlftpfs ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER /mnt/ftp
          - rsync -avz --delete --checksum ./public_html/ /mnt/ftp/public_html
          - fusermount -u /mnt/ftp

  # branches:
  #   main:
  #     - step:
  #         name: Deploy to Test
  #         deployment: test
  #         caches:
  #           - rsync-cache # Nombre válido del caché
  #         script:
  #           # Instalación de curlftpfs y rsync solo si no están en caché
  #           - apt-get update && apt-get install -y curlftpfs rsync # Instala curlftpfs y rsync
  #           - mkdir -p /mnt/ftp
  #           - curlftpfs ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER /mnt/ftp
  #           - rsync -avz --delete --checksum ./public_html/ /mnt/ftp/public_html
  #           - fusermount -u /mnt/ftp

definitions:
  caches:
    rsync-cache: /var/cache/apt/archives # Usamos el directorio de caché de apt
