name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Default Step
        run: echo "This is the default pipeline for testing."

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to Test
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "set ftp:ssl-allow no;
          open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER;
          mirror --reverse --delete --verbose --only-newer --ignore-time --use-cache ./public_html /public_html;"
